//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace MontaPartner.ApiClient.Generated.Endpoints.Countries.Interfaces;

/// <summary>
/// Interface for Client Endpoint.
/// Description: Retrieve a countries. .
/// Operation: GetCountries.
/// </summary>
[GeneratedCode("ApiGenerator", "x.x.x.x")]
public interface IGetCountriesEndpoint
{
    /// <summary>
    /// Execute method.
    /// </summary>
    /// <param name="httpClientName">The http client name.</param>
    /// <param name="cancellationToken">The cancellation token.</param>
    Task<GetCountriesEndpointResult> ExecuteAsync(
        string httpClientName = "MontaPartner-ApiClient",
        CancellationToken cancellationToken = default);
}