//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Monta.ApiClient.Generated.Contracts.ChargeAuthTokens;

/// <summary>
/// Parameters for operation request.
/// Description: Retrieve a charge auth token.
/// Operation: GetChargeAuthToken.
/// </summary>
[GeneratedCode("ApiGenerator", "x.x.x.x")]
public class GetChargeAuthTokenParameters
{
    [Required]
    public long ChargeAuthTokenId { get; set; }

    /// <inheritdoc />
    public override string ToString()
        => $"{nameof(ChargeAuthTokenId)}: {ChargeAuthTokenId}";
}