//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator 2.0.197.51239.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Demo.Api.Generated.Contracts.Users;

/// <summary>
/// Parameters for operation request.
/// Description: Delete user by id.
/// Operation: DeleteUserById.
/// Area: Users.
/// </summary>
[GeneratedCode("ApiGenerator", "2.0.197.51239")]
public class DeleteUserByIdParameters
{
    /// <summary>
    /// Id of the user.
    /// </summary>
    [FromRoute(Name = "id")]
    [Required]
    public Guid Id { get; set; }

    /// <summary>
    /// Converts to string.
    /// </summary>
    public override string ToString()
    {
        return $"{nameof(Id)}: {Id}";
    }
}