//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace ExAsyncEnumerable.Api.Generated;

[SuppressMessage("Design", "CA1040:Avoid empty interfaces", Justification = "OK.")]
[GeneratedCode("ApiGenerator", "x.x.x.x")]
public interface IApiContractAssemblyMarker
{
}