//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Monta.ApiClient.Generated.Contracts.WalletTransactions;

/// <summary>
/// OperatorAdjustmentTransaction.
/// </summary>
[GeneratedCode("ApiGenerator", "x.x.x.x")]
public class OperatorAdjustmentTransaction
{
    /// <summary>
    /// Id of the wallet to transfer from.
    /// </summary>
    [Required]
    public long FromWalletId { get; set; }

    /// <summary>
    /// Id of the wallet to transfer to.
    /// </summary>
    [Required]
    public long ToWalletId { get; set; }

    /// <summary>
    /// Note for the transaction.
    /// </summary>
    public string? Note { get; set; }

    /// <summary>
    /// Currency identifier.
    /// </summary>
    public long CurrencyId { get; set; }

    /// <summary>
    /// Amount to transfer.
    /// </summary>
    public double Amount { get; set; }

    /// <summary>
    /// External Id of this entity, managed by you.
    /// </summary>
    public string? PartnerExternalId { get; set; }

    /// <summary>
    /// Custom JSON payload for this entity, managed by you.
    /// </summary>
    public List<Object>? PartnerCustomPayload { get; set; } = new List<Object>();

    /// <inheritdoc />
    public override string ToString()
        => $"{nameof(FromWalletId)}: {FromWalletId}, {nameof(ToWalletId)}: {ToWalletId}, {nameof(Note)}: {Note}, {nameof(CurrencyId)}: {CurrencyId}, {nameof(Amount)}: {Amount}, {nameof(PartnerExternalId)}: {PartnerExternalId}, {nameof(PartnerCustomPayload)}.Count: {PartnerCustomPayload?.Count ?? 0}";
}