//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Monta.ApiClient.Generated.Contracts.TeamMemberProfiles;

/// <summary>
/// CreateTeamMemberProfile.
/// </summary>
[GeneratedCode("ApiGenerator", "x.x.x.x")]
public class CreateTeamMemberProfile
{
    /// <summary>
    /// Id of the team.
    /// </summary>
    [Range(0, int.MaxValue)]
    public long TeamId { get; set; }

    /// <summary>
    /// The team member profile name.
    /// </summary>
    [Required]
    public string Name { get; set; }

    /// <summary>
    /// The team member profile description.
    /// </summary>
    [Required]
    public string Description { get; set; }

    /// <summary>
    /// Role for team member profile.
    /// </summary>
    [Required]
    public TeamMemberRole Role { get; set; }

    /// <summary>
    /// The price group, when not provided the default team price group will be applied.
    /// </summary>
    public long? PriceGroupId { get; set; }

    /// <summary>
    /// The cost group.
    /// </summary>
    public long? CostGroupId { get; set; }

    /// <summary>
    /// Allows the team applying member profile to configure charge points.
    /// </summary>
    public bool CanConfigureChargePoints { get; set; } = false;

    /// <summary>
    /// Gives the team applying member profile access to pay with team wallet when charging.
    /// </summary>
    public bool CanPayWithTeamWallet { get; set; } = false;

    /// <summary>
    /// Allows the team applying member profile to request sponsoring from this team for their charge point.
    /// </summary>
    public bool CanRequestSponsoring { get; set; } = false;

    /// <summary>
    /// Allows the team applying member profile to view and manage other members settings.
    /// </summary>
    public bool CanManageTeamMembers { get; set; } = false;

    /// <summary>
    /// Who can pay the charging with Wallet?.
    /// </summary>
    [Required]
    public TeamWalletChargePaymentType TeamWalletChargePaymentType { get; set; } = TeamWalletChargePaymentType.None;

    /// <summary>
    /// Gives the team member access to withdraw and deposit from your team wallet to your bank account.
    /// </summary>
    public bool CanManageTeamWallet { get; set; } = false;

    /// <summary>
    /// List of country ids for which the team member can pay for charges.
    /// </summary>
    [Required]
    public List<int> CanPayForChargesCountryIds { get; set; }

    /// <inheritdoc />
    public override string ToString()
        => $"{nameof(TeamId)}: {TeamId}, {nameof(Name)}: {Name}, {nameof(Description)}: {Description}, {nameof(Role)}: ({Role}), {nameof(PriceGroupId)}: {PriceGroupId}, {nameof(CostGroupId)}: {CostGroupId}, {nameof(CanConfigureChargePoints)}: {CanConfigureChargePoints}, {nameof(CanPayWithTeamWallet)}: {CanPayWithTeamWallet}, {nameof(CanRequestSponsoring)}: {CanRequestSponsoring}, {nameof(CanManageTeamMembers)}: {CanManageTeamMembers}, {nameof(TeamWalletChargePaymentType)}: {TeamWalletChargePaymentType}, {nameof(CanManageTeamWallet)}: {CanManageTeamWallet}, {nameof(CanPayForChargesCountryIds)}.Count: {CanPayForChargesCountryIds?.Count ?? 0}";
}