//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace DemoSample.Api.Tests.Endpoints.Files;

[GeneratedCode("ApiGenerator", "x.x.x.x")]
public class GetFileByIdHandlerStub : IGetFileByIdHandler
{
    public Task<GetFileByIdResult> ExecuteAsync(
        GetFileByIdParameters parameters,
        CancellationToken cancellationToken = default)
    {
        var bytes = Encoding.UTF8.GetBytes("Hello World");
        return Task.FromResult(GetFileByIdResult.Ok(bytes, "text/plain", "dummy.txt"));
    }
}