//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace CodeStructure1.Api.Tests.RouteWithDash.MyEndpoints;

[GeneratedCode("ApiGenerator", "x.x.x.x")]
public class GetRouteWithDashHandlerStub : IGetRouteWithDashHandler
{
    public Task<GetRouteWithDashResult> ExecuteAsync(
        CancellationToken cancellationToken = default)
    {
        return Task.FromResult(GetRouteWithDashResult.Ok("Hallo world"));
    }
}