using System.CodeDom.Compiler;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator 1.1.124.0.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Demo.Api.Generated.Contracts.Files
{
    /// <summary>
    /// Parameters for operation request.
    /// Description: Upload a file as OctetStream.
    /// Operation: UploadSingleFileAsFormData.
    /// Area: Files.
    /// </summary>
    [GeneratedCode("ApiGenerator", "1.1.124.0")]
    public class UploadSingleFileAsFormDataParameters
    {
        [FromBody]
        [Required]
        public IFormFile Request { get; set; }

        /// <summary>
        /// Converts to string.
        /// </summary>
        public override string ToString()
        {
            return $"{nameof(Request)}: {Request}";
        }
    }
}