//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Scenario2.Api.Generated.Endpoints
{
    /// <summary>
    /// Endpoint definitions.
    /// Area: Eventargs.
    /// </summary>
    [ApiController]
    [Route("/api/v1/eventArgs")]
    [GeneratedCode("ApiGenerator", "x.x.x.x")]
    public class EventargsController : ControllerBase
    {
        /// <summary>
        /// Description: Get EventArgs List.
        /// Operation: GetEventArgs.
        /// Area: Eventargs.
        /// </summary>
        [HttpGet]
        [ProducesResponseType(typeof(List<Scenario2.Api.Generated.Contracts.Eventargs.EventArgs>), StatusCodes.Status200OK)]
        public Task<ActionResult> GetEventArgsAsync([FromServices] IGetEventArgsHandler handler, CancellationToken cancellationToken)
        {
            if (handler is null)
            {
                throw new ArgumentNullException(nameof(handler));
            }

            return InvokeGetEventArgsAsync(handler, cancellationToken);
        }

        /// <summary>
        /// Description: Get EventArgs By Id.
        /// Operation: GetEventArgsById.
        /// Area: Eventargs.
        /// </summary>
        [HttpGet("{id}")]
        [ProducesResponseType(typeof(Scenario2.Api.Generated.Contracts.Eventargs.EventArgs), StatusCodes.Status200OK)]
        [ProducesResponseType(typeof(string), StatusCodes.Status404NotFound)]
        public Task<ActionResult> GetEventArgsByIdAsync(GetEventArgsByIdParameters parameters, [FromServices] IGetEventArgsByIdHandler handler, CancellationToken cancellationToken)
        {
            if (handler is null)
            {
                throw new ArgumentNullException(nameof(handler));
            }

            return InvokeGetEventArgsByIdAsync(parameters, handler, cancellationToken);
        }

        private static async Task<ActionResult> InvokeGetEventArgsAsync([FromServices] IGetEventArgsHandler handler, CancellationToken cancellationToken)
        {
            return await handler.ExecuteAsync(cancellationToken);
        }

        private static async Task<ActionResult> InvokeGetEventArgsByIdAsync(GetEventArgsByIdParameters parameters, IGetEventArgsByIdHandler handler, CancellationToken cancellationToken)
        {
            return await handler.ExecuteAsync(parameters, cancellationToken);
        }
    }
}