//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Scenario2.Api.Generated.Endpoints;

/// <summary>
/// Endpoint definitions.
/// </summary>
[ApiController]
[Route("/api/v1/pagination")]
[GeneratedCode("ApiGenerator", "x.x.x.x")]
public class PaginationController : ControllerBase
{
    /// <summary>
    /// Description: Your GET endpoint.
    /// Operation: GetPaginatedListOfInts.
    /// </summary>
    [HttpGet("list/int")]
    [ProducesResponseType(typeof(Pagination<int>), StatusCodes.Status200OK)]
    public async Task<ActionResult> GetPaginatedListOfInts(
        [FromServices] IGetPaginatedListOfIntsHandler handler,
        CancellationToken cancellationToken)
        => await handler.ExecuteAsync(cancellationToken);

    /// <summary>
    /// Description: Your GET endpoint.
    /// Operation: GetPaginatedListOfStrings.
    /// </summary>
    [HttpGet("list/string")]
    [ProducesResponseType(typeof(Pagination<string>), StatusCodes.Status200OK)]
    public async Task<ActionResult> GetPaginatedListOfStrings(
        [FromServices] IGetPaginatedListOfStringsHandler handler,
        CancellationToken cancellationToken)
        => await handler.ExecuteAsync(cancellationToken);
}