//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator 2.0.259.29354.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Demo.Api.Generated.Endpoints;

/// <summary>
/// Endpoint definitions.
/// </summary>
[Authorize]
[ApiController]
[Route("/api/v1/eventArgs")]
[GeneratedCode("ApiGenerator", "2.0.259.29354")]
public class EventargsController : ControllerBase
{
    /// <summary>
    /// Description: Get EventArgs List.
    /// Operation: GetEventArgs.
    /// </summary>
    [HttpGet]
    [ProducesResponseType(typeof(List<Demo.Api.Generated.Contracts.Eventargs.EventArgs>), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(ProblemDetails), StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(typeof(ProblemDetails), StatusCodes.Status403Forbidden)]
    public async Task<ActionResult> GetEventArgs(
        [FromServices] IGetEventArgsHandler handler,
        CancellationToken cancellationToken)
        => await handler.ExecuteAsync(cancellationToken);

    /// <summary>
    /// Description: Get EventArgs By Id.
    /// Operation: GetEventArgById.
    /// </summary>
    [HttpGet("{id}")]
    [ProducesResponseType(typeof(Demo.Api.Generated.Contracts.Eventargs.EventArgs), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(ProblemDetails), StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(typeof(ProblemDetails), StatusCodes.Status403Forbidden)]
    [ProducesResponseType(typeof(ProblemDetails), StatusCodes.Status404NotFound)]
    public async Task<ActionResult> GetEventArgById(
        GetEventArgByIdParameters parameters,
        [FromServices] IGetEventArgByIdHandler handler,
        CancellationToken cancellationToken)
        => await handler.ExecuteAsync(parameters, cancellationToken);
}