//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace MontaPartner.ApiClient.Generated.Contracts.CountryAreas;

/// <summary>
/// Parameters for operation request.
/// Description: Retrieve a country area.
/// Operation: GetCountryArea.
/// </summary>
[GeneratedCode("ApiGenerator", "x.x.x.x")]
public class GetCountryAreaParameters
{
    [Required]
    public long Id { get; set; }

    /// <inheritdoc />
    public override string ToString()
        => $"{nameof(Id)}: {Id}";
}