//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Monta.ApiClient.Generated.Contracts.Webhooks;

/// <summary>
/// WebhookEntryErrorPayload.
/// </summary>
[GeneratedCode("ApiGenerator", "x.x.x.x")]
public class WebhookEntryErrorPayload
{
    /// <summary>
    /// error code for the entry.
    /// </summary>
    public string? ErrorCode { get; set; }

    /// <summary>
    /// error message for the entry.
    /// </summary>
    public string? ErrorMessage { get; set; }

    /// <inheritdoc />
    public override string ToString()
        => $"{nameof(ErrorCode)}: {ErrorCode}, {nameof(ErrorMessage)}: {ErrorMessage}";
}