//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Monta.ApiClient.Generated.Contracts.Webhooks;

/// <summary>
/// WebhookEntry.
/// </summary>
[GeneratedCode("ApiGenerator", "x.x.x.x")]
public class WebhookEntry
{
    /// <summary>
    /// Id of the entry.
    /// </summary>
    public long Id { get; set; }

    /// <summary>
    /// Id of the consumer this entry belongs to.
    /// </summary>
    public long ConsumerId { get; set; }

    /// <summary>
    /// Id of the operator this entry belongs to.
    /// </summary>
    public long OperatorId { get; set; }

    [Required]
    public WebhookEntryEventType EventType { get; set; }

    [Required]
    public WebhookEntryPayload Payload { get; set; }

    [Required]
    public WebhookEntryStatus Status { get; set; }

    public WebhookEntryErrorPayload? Error { get; set; }

    /// <summary>
    /// Creation date of this entry.
    /// </summary>
    [Required]
    public DateTimeOffset CreatedAt { get; set; }

    /// <summary>
    /// Update date of this entry.
    /// </summary>
    public DateTimeOffset? UpdatedAt { get; set; }

    /// <inheritdoc />
    public override string ToString()
        => $"{nameof(Id)}: {Id}, {nameof(ConsumerId)}: {ConsumerId}, {nameof(OperatorId)}: {OperatorId}, {nameof(EventType)}: ({EventType}), {nameof(Payload)}: ({Payload}), {nameof(Status)}: ({Status}), {nameof(Error)}: ({Error}), {nameof(CreatedAt)}: ({CreatedAt}), {nameof(UpdatedAt)}: ({UpdatedAt})";
}