//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Structure1.Api.Generated.Orders.MyContracts;

/// <summary>
/// A single order.
/// Hallo description with multiline and no ending dot.
/// </summary>
[GeneratedCode("ApiGenerator", "x.x.x.x")]
public record Order(
    Guid Id,
    string Description,
    DateTimeOffset MyTime,
    DateTimeOffset? MyNullableDateTime,
    DateTimeOffset MyDateTime,
    [property: Range(1.1, 20.2)] double MyNumber,
    bool MyBool,
    [property: Uri] Uri MyUri,
    string MyByte,
    List<string> MyStringList,
    [property: Range(10, int.MaxValue)] long MyLong,
    Address DeliveryAddress,
    [property: EmailAddress] string MyEmail = "a@a.com",
    [property: Range(int.MinValue, 50)] int MyInteger = 15);