//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace MontaPartner.ApiClient.Generated.Contracts.Teams;

/// <summary>
/// Parameters for operation request.
/// Description: Create a team.
/// Operation: PostTeam.
/// </summary>
[GeneratedCode("ApiGenerator", "x.x.x.x")]
public class PostTeamParameters
{
    [Required]
    public CreateTeamDto Request { get; set; }

    /// <inheritdoc />
    public override string ToString()
        => $"{nameof(Request)}: ({Request})";
}