//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator 2.0.235.44759.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Demo.Api.Generated.Contracts.Addresses;

/// <summary>
/// Domain Interface for RequestHandler.
/// Description: Get addresses by postal code.
/// Operation: GetAddressesByPostalCodes.
/// </summary>
[GeneratedCode("ApiGenerator", "2.0.235.44759")]
public interface IGetAddressesByPostalCodesHandler
{
    /// <summary>
    /// Execute method.
    /// </summary>
    /// <param name="parameters">The parameters.</param>
    /// <param name="cancellationToken">The cancellation token.</param>
    Task<GetAddressesByPostalCodesResult> ExecuteAsync(
        GetAddressesByPostalCodesParameters parameters,
        CancellationToken cancellationToken = default);
}