//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace MontaPartner.ApiClient.Generated.Endpoints.WalletTransactions.Interfaces;

/// <summary>
/// Interface for Client Endpoint Result.
/// Description: Patch an existing transaction.
/// Operation: PatchTransaction.
/// </summary>
[GeneratedCode("ApiGenerator", "x.x.x.x")]
public interface IPatchTransactionEndpointResult : IEndpointResponse
{

    bool IsOk { get; }

    bool IsBadRequest { get; }

    bool IsUnauthorized { get; }

    bool IsForbidden { get; }

    WalletTransaction OkContent { get; }

    string? BadRequestContent { get; }

    string? UnauthorizedContent { get; }

    string? ForbiddenContent { get; }
}