//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator 2.0.323.55388.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Demo.Api.Tests.Endpoints.Orders;

[GeneratedCode("ApiGenerator", "2.0.323.55388")]
public class GetOrdersHandlerStub : IGetOrdersHandler
{
    public Task<GetOrdersResult> ExecuteAsync(
        GetOrdersParameters parameters,
        CancellationToken cancellationToken = default)
    {
        var data = new Fixture().Create<List<Order>>();

        var paginationData = new Pagination<Order>(
            data,
            parameters.PageSize,
            parameters.QueryString,
            parameters.ContinuationToken);

        return Task.FromResult(GetOrdersResult.Ok(paginationData));
    }
}