//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace CodeStructure1.ApiClient.Generated.Orders.MyEndpoints.Interfaces;

/// <summary>
/// Interface for Client Endpoint.
/// Description: Update part of order by id.
/// Operation: PatchOrdersId.
/// </summary>
[GeneratedCode("ApiGenerator", "x.x.x.x")]
public interface IPatchOrdersIdEndpoint
{
    /// <summary>
    /// Execute method.
    /// </summary>
    /// <param name="parameters">The parameters.</param>
    /// <param name="httpClientName">The http client name.</param>
    /// <param name="cancellationToken">The cancellation token.</param>
    Task<PatchOrdersIdEndpointResult> ExecuteAsync(
        PatchOrdersIdParameters parameters,
        string httpClientName = "CodeStructure1-ApiClient",
        CancellationToken cancellationToken = default);
}