//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace MontaPartner.ApiClient.Generated.Contracts.TariffRecurringPeriods;

/// <summary>
/// TariffRecurringPeriodCreateRequestDto.
/// </summary>
[GeneratedCode("ApiGenerator", "x.x.x.x")]
public class TariffRecurringPeriodCreateRequestDto
{
    /// <summary>
    /// Id of the tariff this period will belong to.
    /// </summary>
    [Required]
    public long TariffId { get; set; }

    /// <summary>
    /// Id of the tariff period group this period will belong to.
    /// </summary>
    [Required]
    public long GroupId { get; set; }

    [Required]
    public DayOfWeek DayOfWeek { get; set; }

    public DayOfWeek? EndDayOfWeek { get; set; }

    /// <summary>
    /// hour that the period starts at.
    /// </summary>
    [Required]
    public int StartHour { get; set; }

    /// <summary>
    /// hour that the period ends at.
    /// </summary>
    [Required]
    public int EndHour { get; set; }

    /// <summary>
    /// price during the period.
    /// </summary>
    [Required]
    public double Price { get; set; }

    /// <inheritdoc />
    public override string ToString()
        => $"{nameof(TariffId)}: {TariffId}, {nameof(GroupId)}: {GroupId}, {nameof(DayOfWeek)}: ({DayOfWeek}), {nameof(EndDayOfWeek)}: ({EndDayOfWeek}), {nameof(StartHour)}: {StartHour}, {nameof(EndHour)}: {EndHour}, {nameof(Price)}: {Price}";
}