//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace MontaPartner.ApiClient.Generated.Contracts.Insights;

/// <summary>
/// ChargesInsightChargerReportDtoConsumption.
/// </summary>
[GeneratedCode("ApiGenerator", "x.x.x.x")]
public class ChargesInsightChargerReportDtoConsumption
{
    /// <summary>
    /// Number of charging sessions.
    /// </summary>
    [Required]
    public long TotalSessions { get; set; }

    /// <summary>
    /// Sum of all Kwh consumed.
    /// </summary>
    [Required]
    public double TotalKwh { get; set; }

    /// <inheritdoc />
    public override string ToString()
        => $"{nameof(TotalSessions)}: {TotalSessions}, {nameof(TotalKwh)}: {TotalKwh}";
}