//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Structure1.Api.Generated.Orders.MyContracts;

/// <summary>
/// Parameters for operation request.
/// Description: Get orders.
/// Operation: GetOrders.
/// </summary>
[GeneratedCode("ApiGenerator", "x.x.x.x")]
public record GetOrdersParameters(
    [property: FromQuery] string? QueryString,
    [property: FromQuery] string? QueryStringArray,
    [property: FromQuery] string? ContinuationToken,
    [property: FromQuery, Required, Range(1, 100)] int PageSize = 10,
    [property: FromQuery, Range(0, int.MaxValue)] int PageIndex = 0);