//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Structure1.Api.Generated.Orders.MyContracts;

/// <summary>
/// Parameters for operation request.
/// Description: Update part of order by id.
/// Operation: PatchOrdersId.
/// </summary>
[GeneratedCode("ApiGenerator", "x.x.x.x")]
public record PatchOrdersIdParameters(
    [property: FromRoute, Required] Guid Id,
    [property: FromHeader, Required] string MyTestHeader,
    [property: FromHeader, Required] bool MyTestHeaderBool,
    [property: FromHeader, Required] int MyTestHeaderInt,
    [property: FromHeader(Name = "x-correlation-id"), Required] string CorrelationId,
    [property: FromBody, Required] UpdateOrderRequest Request);