//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace GenericPaginationApi.Domain;

[GeneratedCode("ApiGenerator", "x.x.x.x")]
public class DomainRegistration
{
}