//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Monta.ApiClient.Generated.Contracts;

/// <summary>
/// Enumeration: ComponentMetadataTypeDto.
/// </summary>
[GeneratedCode("ApiGenerator", "x.x.x.x")]
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum ComponentMetadataTypeDto
{
    [EnumMember(Value = "tariff-metadata")]
    TariffMetadata,

    [EnumMember(Value = "spot-price-metadata")]
    SpotPriceMetadata,

    [EnumMember(Value = "spot-price-additions-metadata")]
    SpotPriceAdditionsMetadata,

    [EnumMember(Value = "idle-fee-metadata")]
    IdleFeeMetadata,

    [EnumMember(Value = "duration-fee-metadata")]
    DurationFeeMetadata,

    [EnumMember(Value = "default-metadata")]
    DefaultMetadata,
}