//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Monta.ApiClient.Generated.Contracts;

/// <summary>
/// Enumeration: SponsoredChargePointPayoutType.
/// </summary>
[GeneratedCode("ApiGenerator", "x.x.x.x")]
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum SponsoredChargePointPayoutType
{
    [EnumMember(Value = "end-of-month")]
    EndOfMonth,

    [EnumMember(Value = "realtime")]
    Realtime,

    [EnumMember(Value = "other")]
    Other,
}