//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace CodeStructure1.ApiClient.Generated.MyContracts;

/// <summary>
/// Enumeration: GenderType.
/// </summary>
[GeneratedCode("ApiGenerator", "x.x.x.x")]
public enum GenderType
{
    None,
    NonBinary,
    Male,
    Female,
}