openapi: 3.0.0
info:
  $ref: ../common/components/endpoints.v1.yaml#/info
servers:
  $ref: ../common/components/endpoints.v1.yaml#/servers

paths:
  '/orders/{id}':
    get:
      tags:
        - Orders
      summary: Get order by id
      description: Get order by id
      operationId: getOrderById
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the order to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          $ref: ../common/components/responses.v1.yaml#/400
        '404':
          $ref: ../common/components/responses.v1.yaml#/404
        default:
          $ref: ../common/components/responses.v1.yaml#/400
components:
  schemas:
    Order:
      $ref: ./models/order.v1.yaml
    Orders:
      type: array
      items:
        $ref: '#/components/schemas/Order'
      x-tags:
        - Orders
      title: Orders
      description: A list of orders.
