//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Monta.ApiClient.Generated.Contracts.Auth;

/// <summary>
/// Parameters for operation request.
/// Description: Obtain your `accessToken`.
/// Operation: GetAccessTokenWithClientCredentials.
/// </summary>
[GeneratedCode("ApiGenerator", "x.x.x.x")]
public class GetAccessTokenWithClientCredentialsParameters
{
    [Required]
    public string? Request { get; set; }

    /// <inheritdoc />
    public override string ToString()
        => $"{nameof(Request)}: ({Request})";
}