//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator 2.0.259.29354.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Demo.Api.Generated.Contracts.Files;

/// <summary>
/// Parameters for operation request.
/// Description: Get File By Id.
/// Operation: GetFileById.
/// </summary>
[GeneratedCode("ApiGenerator", "2.0.259.29354")]
public class GetFileByIdParameters
{
    /// <summary>
    /// The file id.
    /// </summary>
    [FromRoute(Name = "id")]
    [Required]
    public string Id { get; set; }

    /// <inheritdoc />
    public override string ToString()
        => $"{nameof(Id)}: {Id}";
}