//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Monta.ApiClient.Generated.Endpoints.TeamMembers.Interfaces;

/// <summary>
/// Interface for Client Endpoint Result.
/// Description: Patch a team member.
/// Operation: PatchTeamMember.
/// </summary>
[GeneratedCode("ApiGenerator", "x.x.x.x")]
public interface IPatchTeamMemberEndpointResult : IEndpointResponse
{

    bool IsOk { get; }

    bool IsBadRequest { get; }

    bool IsUnauthorized { get; }

    TeamMemberDto OkContent { get; }

    string? BadRequestContent { get; }

    string? UnauthorizedContent { get; }
}