//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace DemoSampleApi.ApiClient.Generated.Endpoints;

/// <summary>
/// Interface for Client Endpoint Result.
/// Description: Your GET endpoint.
/// Operation: GetRouteWithDash.
/// </summary>
[GeneratedCode("ApiGenerator", "x.x.x.x")]
public interface IGetRouteWithDashEndpointResult : IEndpointResponse
{
    bool IsOk { get; }

    bool IsUnauthorized { get; }

    bool IsForbidden { get; }

    bool IsInternalServerError { get; }

    string OkContent { get; }

    string InternalServerErrorContent { get; }
}