//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator 1.1.405.0.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Demo.Api.Generated.Contracts.Eventargs
{
    /// <summary>
    /// Domain Interface for RequestHandler.
    /// Description: Get EventArgs List.
    /// Operation: GetEventArgs.
    /// Area: Eventargs.
    /// </summary>
    [GeneratedCode("ApiGenerator", "1.1.405.0")]
    public interface IGetEventArgsHandler
    {
        /// <summary>
        /// Execute method.
        /// </summary>
        /// <param name="cancellationToken">The cancellation token.</param>
        Task<GetEventArgsResult> ExecuteAsync(CancellationToken cancellationToken = default);
    }
}