//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Scenario2.Api.Generated.Contracts;

[SuppressMessage("Maintainability Rules", "SA1413:Use trailing comma in multi-line initializers", Justification = "OK.")]
public enum GenderType
{
    None,
    NonBinary,
    Male,
    Female
}