//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Structure1.Api.Generated.Items.MyContracts;

/// <summary>
/// Parameters for operation request.
/// Description: Create a new item.
/// Operation: CreateItem.
/// </summary>
[GeneratedCode("ApiGenerator", "x.x.x.x")]
public record CreateItemParameters(
    [property: FromBody, Required] CreateItemRequest Request);