//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator 2.0.413.49179.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Demo.Api.Generated.Contracts.Users;

/// <summary>
/// Request to create a user.
/// </summary>
[GeneratedCode("ApiGenerator", "2.0.413.49179")]
public class CreateUserRequest
{
    [Required]
    public string FirstName { get; set; }

    [Required]
    public string LastName { get; set; }

    public DateTimeOffset? MyNullableDateTime { get; set; }

    [Required]
    public DateTimeOffset MyDateTime { get; set; }

    /// <summary>
    /// Undefined description.
    /// </summary>
    /// <remarks>
    /// Email validation being enforced.
    /// </remarks>
    [Required]
    [EmailAddress]
    public string Email { get; set; }

    /// <summary>
    /// Undefined description.
    /// </summary>
    /// <remarks>
    /// Url validation being enforced.
    /// </remarks>
    [Uri]
    public Uri Homepage { get; set; }

    /// <summary>
    /// GenderType.
    /// </summary>
    [Required]
    public GenderType Gender { get; set; }

    public Address? MyNullableAddress { get; set; }

    [Required]
    public Dictionary<string, string> Tags { get; set; }

    public Dictionary<string, string> DesiredProperties1 { get; set; }

    public Dictionary<string, string>? DesiredProperties2 { get; set; }

    public Dictionary<string, int>? DesiredProperties3 { get; set; }

    /// <inheritdoc />
    public override string ToString()
        => $"{nameof(FirstName)}: {FirstName}, {nameof(LastName)}: {LastName}, {nameof(MyNullableDateTime)}: ({MyNullableDateTime}), {nameof(MyDateTime)}: ({MyDateTime}), {nameof(Email)}: {Email}, {nameof(Homepage)}: ({Homepage}), {nameof(Gender)}: {Gender}, {nameof(MyNullableAddress)}: ({MyNullableAddress}), {nameof(Tags)}: ({Tags}), {nameof(DesiredProperties1)}: ({DesiredProperties1}), {nameof(DesiredProperties2)}: ({DesiredProperties2}), {nameof(DesiredProperties3)}: ({DesiredProperties3})";
}