using System.CodeDom.Compiler;

//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator 2.0.121.412.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Demo.Api.Generated.Contracts.Users
{
    /// <summary>
    /// Update test-gender Request.
    /// </summary>
    [GeneratedCode("ApiGenerator", "2.0.121.412")]
    public class UpdateTestGenderRequest
    {
        /// <summary>
        /// GenderType.
        /// </summary>
        public GenderType Gender { get; set; }

        /// <summary>
        /// Converts to string.
        /// </summary>
        public override string ToString()
        {
            return $"{nameof(Gender)}: ({Gender})";
        }
    }
}