//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Monta.ApiClient.Generated.Contracts.PriceGroups;

/// <summary>
/// Parameters for operation request.
/// Description: Creates a price group.
/// Operation: CreatePriceGroup.
/// </summary>
[GeneratedCode("ApiGenerator", "x.x.x.x")]
public class CreatePriceGroupParameters
{
    [Required]
    public CreateOrUpdatePriceGroupDto Request { get; set; }

    /// <inheritdoc />
    public override string ToString()
        => $"{nameof(Request)}: ({Request})";
}