//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator 2.0.197.51239.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Demo.Api.Generated.Contracts.RouteWithDash;

/// <summary>
/// Domain Interface for RequestHandler.
/// Description: Your GET endpoint.
/// Operation: GetRouteWithDash.
/// Area: RouteWithDash.
/// </summary>
[GeneratedCode("ApiGenerator", "2.0.197.51239")]
public interface IGetRouteWithDashHandler
{
    /// <summary>
    /// Execute method.
    /// </summary>
    /// <param name="cancellationToken">The cancellation token.</param>
    Task<GetRouteWithDashResult> ExecuteAsync(CancellationToken cancellationToken = default);
}