//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace PetStoreApi.ApiClient.Generated.Endpoints.Pets.Interfaces;

/// <summary>
/// Interface for Client Endpoint Result.
/// Description: Info for a specific pet.
/// Operation: ShowPetById.
/// </summary>
[GeneratedCode("ApiGenerator", "x.x.x.x")]
public interface IShowPetByIdEndpointResult : IEndpointResponse
{
    bool IsOk { get; }

    bool IsBadRequest { get; }

    bool IsUnauthorized { get; }

    bool IsForbidden { get; }

    bool IsInternalServerError { get; }

    Pet OkContent { get; }

    ValidationProblemDetails BadRequestContent { get; }

    string InternalServerErrorContent { get; }
}