using System.CodeDom.Compiler;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Scenario2.Api.Generated.Contracts.Files
{
    /// <summary>
    /// Parameters for operation request.
    /// Description: Upload a file as OctetStream.
    /// Operation: UploadSingleFileAsFormData.
    /// Area: Files.
    /// </summary>
    [GeneratedCode("ApiGenerator", "x.x.x.x")]
    public class UploadSingleFileAsFormDataParameters
    {
        [FromBody]
        [Required]
        public IFormFile Request { get; set; }

        /// <summary>
        /// Converts to string.
        /// </summary>
        public override string ToString()
        {
            return $"{nameof(Request)}: {Request}";
        }
    }
}