//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace ExampleWithAllResponseTypes.ApiClient.Generated.Endpoints.Example.Interfaces;

/// <summary>
/// Interface for Client Endpoint Result.
/// Description: Example endpoint.
/// Operation: GetExample.
/// </summary>
[GeneratedCode("ApiGenerator", "x.x.x.x")]
public interface IGetExampleEndpointResult : IEndpointResponse
{
    bool IsOk { get; }

    bool IsMultipleChoices { get; }

    bool IsMovedPermanently { get; }

    bool IsFound { get; }

    bool IsSeeOther { get; }

    bool IsNotModified { get; }

    bool IsUseProxy { get; }

    bool IsUnused { get; }

    bool IsRedirectKeepVerb { get; }

    bool IsPermanentRedirect { get; }

    bool IsBadRequest { get; }

    bool IsUnauthorized { get; }

    bool IsPaymentRequired { get; }

    bool IsForbidden { get; }

    bool IsNotFound { get; }

    bool IsMethodNotAllowed { get; }

    bool IsNotAcceptable { get; }

    bool IsProxyAuthenticationRequired { get; }

    bool IsRequestTimeout { get; }

    bool IsConflict { get; }

    bool IsGone { get; }

    bool IsLengthRequired { get; }

    bool IsPreconditionFailed { get; }

    bool IsRequestEntityTooLarge { get; }

    bool IsRequestUriTooLong { get; }

    bool IsUnsupportedMediaType { get; }

    bool IsRequestedRangeNotSatisfiable { get; }

    bool IsExpectationFailed { get; }

    bool Is418 { get; }

    bool IsMisdirectedRequest { get; }

    bool IsUnprocessableEntity { get; }

    bool IsLocked { get; }

    bool IsFailedDependency { get; }

    bool Is425 { get; }

    bool IsUpgradeRequired { get; }

    bool IsPreconditionRequired { get; }

    bool IsTooManyRequests { get; }

    bool IsRequestHeaderFieldsTooLarge { get; }

    bool IsUnavailableForLegalReasons { get; }

    bool IsInternalServerError { get; }

    bool IsNotImplemented { get; }

    bool IsBadGateway { get; }

    bool IsServiceUnavailable { get; }

    bool IsGatewayTimeout { get; }

    bool IsHttpVersionNotSupported { get; }

    bool IsVariantAlsoNegotiates { get; }

    bool IsInsufficientStorage { get; }

    bool IsLoopDetected { get; }

    bool IsNotExtended { get; }

    bool IsNetworkAuthenticationRequired { get; }

    ExampleModel OkContent { get; }

    string MultipleChoicesContent { get; }

    string MovedPermanentlyContent { get; }

    string FoundContent { get; }

    string SeeOtherContent { get; }

    string UseProxyContent { get; }

    string UnusedContent { get; }

    string RedirectKeepVerbContent { get; }

    string PermanentRedirectContent { get; }

    ValidationProblemDetails BadRequestContent { get; }

    string PaymentRequiredContent { get; }

    string NotFoundContent { get; }

    string MethodNotAllowedContent { get; }

    string NotAcceptableContent { get; }

    string ProxyAuthenticationRequiredContent { get; }

    string RequestTimeoutContent { get; }

    string ConflictContent { get; }

    string GoneContent { get; }

    string LengthRequiredContent { get; }

    string PreconditionFailedContent { get; }

    string RequestEntityTooLargeContent { get; }

    string RequestUriTooLongContent { get; }

    string UnsupportedMediaTypeContent { get; }

    string RequestedRangeNotSatisfiableContent { get; }

    string ExpectationFailedContent { get; }

    string 418Content { get; }

    string MisdirectedRequestContent { get; }

    string UnprocessableEntityContent { get; }

    string LockedContent { get; }

    string FailedDependencyContent { get; }

    string 425Content { get; }

    string UpgradeRequiredContent { get; }

    string PreconditionRequiredContent { get; }

    string TooManyRequestsContent { get; }

    string RequestHeaderFieldsTooLargeContent { get; }

    string UnavailableForLegalReasonsContent { get; }

    string InternalServerErrorContent { get; }

    string NotImplementedContent { get; }

    string BadGatewayContent { get; }

    string ServiceUnavailableContent { get; }

    string GatewayTimeoutContent { get; }

    string HttpVersionNotSupportedContent { get; }

    string VariantAlsoNegotiatesContent { get; }

    string InsufficientStorageContent { get; }

    string LoopDetectedContent { get; }

    string NotExtendedContent { get; }

    string NetworkAuthenticationRequiredContent { get; }
}
