//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace ExGenericPagination.Api.Generated.Contracts.Cats;

/// <summary>
/// Domain Interface for RequestHandler.
/// Description: Find all cats.
/// Operation: GetCats.
/// </summary>
[GeneratedCode("ApiGenerator", "x.x.x.x")]
public interface IGetCatsHandler
{
    /// <summary>
    /// Execute method.
    /// </summary>
    /// <param name="parameters">The parameters.</param>
    /// <param name="cancellationToken">The cancellation token.</param>
    Task<GetCatsResult> ExecuteAsync(
        GetCatsParameters parameters,
        CancellationToken cancellationToken = default);
}
