//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace TestUnit.Task.NsApi.Api.Tests.Endpoints.Tasks;

[GeneratedCode("ApiGenerator", "x.x.x.x")]
public class GetTasksHandlerStub : TestUnit.Task.NsApi.Api.Generated.Contracts.Tasks.IGetTasksHandler
{
    public Task<TestUnit.Task.NsApi.Api.Generated.Contracts.Tasks.GetTasksResult> ExecuteAsync(
        CancellationToken cancellationToken = default)
    {
        var data = new Fixture().Create<List<TestUnit.Task.NsApi.Api.Generated.Contracts.Tasks.Task>>();

        return System.Threading.Tasks.Task.FromResult(TestUnit.Task.NsApi.Api.Generated.Contracts.Tasks.GetTasksResult.Ok(data));
    }
}