//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Monta.ApiClient.Generated.Contracts.Prices;

/// <summary>
/// Parameters for operation request.
/// Description: Retrieve prices forecast.
/// Operation: GetPricesForecast.
/// </summary>
[GeneratedCode("ApiGenerator", "x.x.x.x")]
public class GetPricesForecastParameters
{
    [Range(0, 2147483647)]
    public long ChargePointId { get; set; }

    [Range(0, 2147483647)]
    public long? PriceGroupId { get; set; }

    public long? TeamMemberId { get; set; }

    /// <inheritdoc />
    public override string ToString()
        => $"{nameof(ChargePointId)}: {ChargePointId}, {nameof(PriceGroupId)}: {PriceGroupId}, {nameof(TeamMemberId)}: {TeamMemberId}";
}