//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace MontaPartner.ApiClient.Generated.Contracts.ChargePoints;

/// <summary>
/// Parameters for operation request.
/// Description: Retrieve charge points / sites for map.
/// Operation: GetChargePointMap.
/// </summary>
[GeneratedCode("ApiGenerator", "x.x.x.x")]
public class GetChargePointMapParameters
{
    [Required]
    public double TopLatitude { get; set; }

    [Required]
    public double RightLongitude { get; set; }

    [Required]
    public double BottomLatitude { get; set; }

    [Required]
    public double LeftLongitude { get; set; }

    [Required]
    public double CenterLatitude { get; set; }

    [Required]
    public double CenterLongitude { get; set; }

    [Required]
    public double Zoom { get; set; }

    [Required]
    public bool? IncludeBusy { get; set; } = true;

    [Required]
    public bool? IncludeAllOperators { get; set; } = false;

    /// <inheritdoc />
    public override string ToString()
        => $"{nameof(TopLatitude)}: {TopLatitude}, {nameof(RightLongitude)}: {RightLongitude}, {nameof(BottomLatitude)}: {BottomLatitude}, {nameof(LeftLongitude)}: {LeftLongitude}, {nameof(CenterLatitude)}: {CenterLatitude}, {nameof(CenterLongitude)}: {CenterLongitude}, {nameof(Zoom)}: {Zoom}, {nameof(IncludeBusy)}: {IncludeBusy}, {nameof(IncludeAllOperators)}: {IncludeAllOperators}";
}