//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Monta.ApiClient.Generated.Contracts.PriceGroups;

/// <summary>
/// CreateAdditionalPricingDto.
/// </summary>
[GeneratedCode("ApiGenerator", "x.x.x.x")]
public class CreateAdditionalPricingDto
{
    /// <summary>
    /// Type of the additional pricing. `absolute` means the value is a price.
    /// </summary>
    [Required]
    public AdditionalPricingType Type { get; set; }

    /// <summary>
    /// The value of this additional pricing.
    /// </summary>
    [Required]
    [Range(0, double.MaxValue)]
    public double Value { get; set; }

    /// <summary>
    /// A title for this additional pricing.
    /// </summary>
    public string? Title { get; set; }

    /// <inheritdoc />
    public override string ToString()
        => $"{nameof(Type)}: ({Type}), {nameof(Value)}: {Value}, {nameof(Title)}: {Title}";
}