//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Monta.ApiClient.Generated.Contracts;

/// <summary>
/// MontaPageMeta.
/// </summary>
[GeneratedCode("ApiGenerator", "x.x.x.x")]
public class MontaPageMeta
{
    [Required]
    public int ItemCount { get; set; }

    [Required]
    public int CurrentPage { get; set; }

    [Required]
    public int PerPage { get; set; }

    [Required]
    public int TotalPageCount { get; set; }

    [Required]
    public long TotalItemCount { get; set; }

    /// <inheritdoc />
    public override string ToString()
        => $"{nameof(ItemCount)}: {ItemCount}, {nameof(CurrentPage)}: {CurrentPage}, {nameof(PerPage)}: {PerPage}, {nameof(TotalPageCount)}: {TotalPageCount}, {nameof(TotalItemCount)}: {TotalItemCount}";
}