//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator 1.1.405.0.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Demo.Domain
{
    [GeneratedCode("ApiGenerator", "1.1.405.0")]
    public class DomainRegistration
    {
    }
}