//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Structure1.Api.Generated.Tasks.MyContracts;

/// <summary>
/// Describes a single task.
/// </summary>
[GeneratedCode("ApiGenerator", "x.x.x.x")]
public record Task(
    Guid Id,
    string Name);