//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Monta.ApiClient.Generated.Contracts.Sites;

/// <summary>
/// Parameters for operation request.
/// Description: Patch an existing (charge) site.
/// Operation: PatchSite.
/// </summary>
[GeneratedCode("ApiGenerator", "x.x.x.x")]
public class PatchSiteParameters
{
    [Required]
    public long SiteId { get; set; }

    [Required]
    public PatchSite Request { get; set; }

    /// <inheritdoc />
    public override string ToString()
        => $"{nameof(SiteId)}: {SiteId}, {nameof(Request)}: ({Request})";
}