//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace PetStore.ApiClient.Generated.Endpoints.Pets.Interfaces;

/// <summary>
/// Interface for Client Endpoint Result.
/// Description: List all pets.
/// Operation: ListPets.
/// </summary>
[GeneratedCode("ApiGenerator", "x.x.x.x")]
public interface IListPetsEndpointResult : IEndpointResponse
{

    bool IsOk { get; }

    bool IsBadRequest { get; }

    IEnumerable<Pet> OkContent { get; }

    string? BadRequestContent { get; }
}