//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Monta.ApiClient.Generated.Contracts.Charges;

/// <summary>
/// ChargesInsightSummary.
/// </summary>
[GeneratedCode("ApiGenerator", "x.x.x.x")]
public class ChargesInsightSummary
{
    /// <summary>
    /// The total kWh charged for this entry.
    /// </summary>
    [Required]
    public double TotalKwh { get; set; }

    /// <summary>
    /// The total price for this entry.
    /// </summary>
    [Required]
    public long TotalPrice { get; set; }

    /// <summary>
    /// The total cost for this entry.
    /// </summary>
    [Required]
    public long TotalCost { get; set; }

    /// <summary>
    /// The total sessions for this entry.
    /// </summary>
    [Required]
    public long TotalSessions { get; set; }

    /// <inheritdoc />
    public override string ToString()
        => $"{nameof(TotalKwh)}: {TotalKwh}, {nameof(TotalPrice)}: {TotalPrice}, {nameof(TotalCost)}: {TotalCost}, {nameof(TotalSessions)}: {TotalSessions}";
}