//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Monta.ApiClient.Generated.Contracts.Charges;

/// <summary>
/// DetailedBreakdown.
/// </summary>
[GeneratedCode("ApiGenerator", "x.x.x.x")]
public class DetailedBreakdown
{
    /// <summary>
    /// The summary of the total prices for this breakdown.
    /// </summary>
    [Required]
    public BreakdownSummary Summary { get; set; }

    /// <summary>
    /// The currency applicable for this breakdown (for all the components: prices, fees, adjustments).
    /// </summary>
    [Required]
    public Currency9 Currency { get; set; }

    /// <summary>
    /// The breakdown entries for this breakdown, currently organized on an hourly basis.
    /// </summary>
    [Required]
    public List<Breakdown> Breakdown { get; set; }

    /// <summary>
    /// The fees that compose this breakdown.
    /// </summary>
    [Required]
    public List<Component> Fees { get; set; }

    /// <summary>
    /// The adjustments applied for this breakdown.
    /// </summary>
    [Required]
    public List<Component> Adjustments { get; set; }

    /// <inheritdoc />
    public override string ToString()
        => $"{nameof(Summary)}: ({Summary}), {nameof(Currency)}: ({Currency}), {nameof(Breakdown)}.Count: {Breakdown?.Count ?? 0}, {nameof(Fees)}.Count: {Fees?.Count ?? 0}, {nameof(Adjustments)}.Count: {Adjustments?.Count ?? 0}";
}