//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace DemoUsersApi.Api.Tests.Endpoints.Users;

[GeneratedCode("ApiGenerator", "x.x.x.x")]
public class UpdateUserByIdHandlerStub : IUpdateUserByIdHandler
{
    public Task<UpdateUserByIdResult> ExecuteAsync(
        UpdateUserByIdParameters parameters,
        CancellationToken cancellationToken = default)
    {
        return Task.FromResult(UpdateUserByIdResult.Ok("Hallo world"));
    }
}