//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace MontaPartner.ApiClient.Generated.Contracts;

/// <summary>
/// Operator.
/// </summary>
[GeneratedCode("ApiGenerator", "x.x.x.x")]
public class Operator
{
    /// <summary>
    /// ID of the operator.
    /// </summary>
    public long Id { get; set; }

    /// <summary>
    /// Name of operator.
    /// </summary>
    [Required]
    public string Name { get; set; }

    /// <summary>
    /// Identifier of operator.
    /// </summary>
    [Required]
    public string Identifier { get; set; }

    /// <summary>
    /// Partner id (owner of this operator).
    /// </summary>
    public long? PartnerId { get; set; }

    /// <summary>
    /// VAT number.
    /// </summary>
    public string? VatNumber { get; set; }

    /// <inheritdoc />
    public override string ToString()
        => $"{nameof(Id)}: {Id}, {nameof(Name)}: {Name}, {nameof(Identifier)}: {Identifier}, {nameof(PartnerId)}: {PartnerId}, {nameof(VatNumber)}: {VatNumber}";
}