//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace MontaPartner.ApiClient.Generated.Contracts;

/// <summary>
/// PriceGroupAppliedTo.
/// </summary>
[GeneratedCode("ApiGenerator", "x.x.x.x")]
public class PriceGroupAppliedTo
{
    /// <summary>
    /// Id's of the ChargePoints this Pricegroup has been applied to.
    /// </summary>
    [Required]
    public List<long> ChargePoints { get; set; }

    /// <summary>
    /// Id's of the Sites this Pricegroup has been applied to.
    /// </summary>
    [Required]
    public List<long> Sites { get; set; }

    /// <summary>
    /// Id's of the Team Members this Pricegroup has been applied to.
    /// </summary>
    [Required]
    public List<long> TeamMembers { get; set; }

    /// <inheritdoc />
    public override string ToString()
        => $"{nameof(ChargePoints)}.Count: {ChargePoints?.Count ?? 0}, {nameof(Sites)}.Count: {Sites?.Count ?? 0}, {nameof(TeamMembers)}.Count: {TeamMembers?.Count ?? 0}";
}