//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace TestProject.AtcTest.Contracts.Test
{
    /// <summary>
    /// Results for operation request.
    /// Description: Get.
    /// Operation: Get.
    /// Area: Test.
    /// </summary>
    [GeneratedCode("ApiGenerator", "x.x.x.x")]
    public class GetResult : ResultBase
    {
        private GetResult(ActionResult result) : base(result) { }

        /// <summary>
        /// 200 - Ok response.
        /// </summary>
        public static GetResult Ok(IEnumerable<string> response) => new GetResult(new OkObjectResult(response ?? Enumerable.Empty<string>()));

        /// <summary>
        /// Performs an implicit conversion from GetResult to ActionResult.
        /// </summary>
        public static implicit operator GetResult(List<string> response) => Ok(response);
    }
}