//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator 2.0.235.44759.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Demo.Api.Generated.Contracts.Orders;

/// <summary>
/// Domain Interface for RequestHandler.
/// Description: Update part of order by id.
/// Operation: PatchOrdersId.
/// </summary>
[GeneratedCode("ApiGenerator", "2.0.235.44759")]
public interface IPatchOrdersIdHandler
{
    /// <summary>
    /// Execute method.
    /// </summary>
    /// <param name="parameters">The parameters.</param>
    /// <param name="cancellationToken">The cancellation token.</param>
    Task<PatchOrdersIdResult> ExecuteAsync(
        PatchOrdersIdParameters parameters,
        CancellationToken cancellationToken = default);
}