//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Structure1.Api.Tests.Tasks.MyEndpoints;

[GeneratedCode("ApiGenerator", "x.x.x.x")]
public class GetTasksHandlerStub : Structure1.Api.Tests.Tasks.MyEndpoints.IGetTasksHandler
{
    public Task<Structure1.Api.Tests.Tasks.MyEndpoints.GetTasksResult> ExecuteAsync(
        CancellationToken cancellationToken = default)
    {
        var data = new Fixture().Create<List<Structure1.Api.Tests.Tasks.MyEndpoints.Task>>();

        return Task.FromResult(Structure1.Api.Tests.Tasks.MyEndpoints.GetTasksResult.Ok(data));
    }
}