//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Monta.ApiClient.Generated.Contracts.NestedTeams;

/// <summary>
/// Parameters for operation request.
/// Description: Reject a nested team invitation.
/// Operation: RejectInvite.
/// </summary>
[GeneratedCode("ApiGenerator", "x.x.x.x")]
public class RejectInviteParameters
{
    [Required]
    [Range(0, 2147483647)]
    public long RelationId { get; set; }

    /// <inheritdoc />
    public override string ToString()
        => $"{nameof(RelationId)}: {RelationId}";
}