//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Monta.ApiClient.Generated.Contracts.Webhooks;

/// <summary>
/// Parameters for operation request.
/// Description: Retrieve webhook entries.
/// Operation: GetWebhookEntries.
/// </summary>
[GeneratedCode("ApiGenerator", "x.x.x.x")]
public class GetWebhookEntriesParameters
{
    /// <summary>
    /// page number to retrieve (starts with 0).
    /// </summary>
    public int Page { get; set; } = 0;

    /// <summary>
    /// number of items per page (between 1 and 100, default 10).
    /// </summary>
    public int PerPage { get; set; } = 10;

    /// <summary>
    /// The status from which webhook entries will be filtered by.
    /// </summary>
    public long Status { get; set; }

    /// <inheritdoc />
    public override string ToString()
        => $"{nameof(Page)}: {Page}, {nameof(PerPage)}: {PerPage}, {nameof(Status)}: {Status}";
}