//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace DemoSampleApi.Api.Tests.Endpoints.Accounts;

[GeneratedCode("ApiGenerator", "x.x.x.x")]
public class UpdateAccountNameHandlerStub : IUpdateAccountNameHandler
{
    public Task<UpdateAccountNameResult> ExecuteAsync(
        UpdateAccountNameParameters parameters,
        CancellationToken cancellationToken = default)
    {
        return Task.FromResult(UpdateAccountNameResult.Ok("Hallo world"));
    }
}