//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Monta.ApiClient.Generated.Contracts.InstallerJobs;

/// <summary>
/// Parameters for operation request.
/// Description: Delete an existing installer job.
/// Operation: DeleteInstallerJob.
/// </summary>
[GeneratedCode("ApiGenerator", "x.x.x.x")]
public class DeleteInstallerJobParameters
{
    [Required]
    public long InstallerJobId { get; set; }

    /// <inheritdoc />
    public override string ToString()
        => $"{nameof(InstallerJobId)}: {InstallerJobId}";
}