//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Monta.ApiClient.Generated.Contracts.InstallerJobs;

/// <summary>
/// Parameters for operation request.
/// Description: Create an installer job.
/// Operation: PostInstallerJob.
/// </summary>
[GeneratedCode("ApiGenerator", "x.x.x.x")]
public class PostInstallerJobParameters
{
    [Required]
    public CreateInstallerJobDto Request { get; set; }

    /// <inheritdoc />
    public override string ToString()
        => $"{nameof(Request)}: ({Request})";
}