//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Monta.ApiClient.Generated.Endpoints.ChargePointStatistics.Interfaces;

/// <summary>
/// Interface for Client Endpoint Result.
/// Description: Retrieve statistics related to a site.
/// Operation: GetSiteStatistics.
/// </summary>
[GeneratedCode("ApiGenerator", "x.x.x.x")]
public interface IGetSiteStatisticsEndpointResult : IEndpointResponse
{

    bool IsOk { get; }

    bool IsBadRequest { get; }

    bool IsUnauthorized { get; }

    bool IsForbidden { get; }

    bool IsNotFound { get; }

    ChargePointStatisticsDto OkContent { get; }

    string? BadRequestContent { get; }

    string? UnauthorizedContent { get; }

    string? ForbiddenContent { get; }

    string? NotFoundContent { get; }
}