//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Monta.ApiClient.Generated.Contracts.Insights;

/// <summary>
/// ChargesInsightDriverReport.
/// </summary>
[GeneratedCode("ApiGenerator", "x.x.x.x")]
public class ChargesInsightDriverReport
{
    /// <summary>
    /// Team ID used for this report.
    /// </summary>
    [Required]
    public long TeamId { get; set; }

    /// <summary>
    /// Team Member ID of the Driver.
    /// </summary>
    [Required]
    public long TeamMemberId { get; set; }

    /// <summary>
    /// User ID of the Driver.
    /// </summary>
    [Required]
    public long UserId { get; set; }

    /// <summary>
    /// Charge consumptions grouped by `chargeType`.
    /// </summary>
    [Required]
    public List<ChargesInsightDriverReportDtoConsumption> Consumptions { get; set; }

    /// <inheritdoc />
    public override string ToString()
        => $"{nameof(TeamId)}: {TeamId}, {nameof(TeamMemberId)}: {TeamMemberId}, {nameof(UserId)}: {UserId}, {nameof(Consumptions)}.Count: {Consumptions?.Count ?? 0}";
}