//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Monta.ApiClient.Generated.Contracts.Insights;

/// <summary>
/// ChargesInsightDriverMemberCostsReportDtoConsumption.
/// </summary>
[GeneratedCode("ApiGenerator", "x.x.x.x")]
public class ChargesInsightDriverMemberCostsReportDtoConsumption
{
    /// <summary>
    /// Defines the type of charge, ie. if it was a sponsored or public charge.
    /// definitions:
    /// * `sponsored` - Charges that have been sponsored.
    /// * `team-operator` - Charges that belong to Charge Points of the same operator as paying team operator.
    /// * `public` - Any charge that was paid for by this team that does not match the other cases.
    /// Note that more chargeTypes might be added in the future. Make sure to handle this gracefully.
    /// </summary>
    [Required]
    public string ChargeType { get; set; }

    /// <summary>
    /// Number of charging sessions.
    /// </summary>
    [Required]
    public long TotalSessions { get; set; }

    /// <summary>
    /// Sum of all Kwh consumed.
    /// </summary>
    [Required]
    public double TotalKwh { get; set; }

    /// <summary>
    /// Sum of all charge net prices.
    /// </summary>
    [Required]
    public double TotalNetPrice { get; set; }

    /// <summary>
    /// Sum of all charge vat amounts.
    /// </summary>
    [Required]
    public double TotalVat { get; set; }

    /// <summary>
    /// Sum of all charge gross prices.
    /// </summary>
    [Required]
    public double TotalGrossPrice { get; set; }

    /// <summary>
    /// The ID of the Member Cost Group applied to this charges, or Null if none.
    /// </summary>
    public long? MemberCostGroupId { get; set; }

    /// <summary>
    /// The name of the Member Cost Group applied to this charges, or Null if none.
    /// </summary>
    public string? MemberCostGroupName { get; set; }

    /// <summary>
    /// Sum of all charge costs in the Member Cost Group currency, or Null if none.
    /// </summary>
    public double? MemberCostGroupPrice { get; set; }

    /// <summary>
    /// Breakdown of the charges by country.
    /// </summary>
    [Required]
    public List<ChargesInsightDriverMemberCostsReportDtoConsumptionCountryBreakdown> CountryBreakdown { get; set; }

    /// <inheritdoc />
    public override string ToString()
        => $"{nameof(ChargeType)}: {ChargeType}, {nameof(TotalSessions)}: {TotalSessions}, {nameof(TotalKwh)}: {TotalKwh}, {nameof(TotalNetPrice)}: {TotalNetPrice}, {nameof(TotalVat)}: {TotalVat}, {nameof(TotalGrossPrice)}: {TotalGrossPrice}, {nameof(MemberCostGroupId)}: {MemberCostGroupId}, {nameof(MemberCostGroupName)}: {MemberCostGroupName}, {nameof(MemberCostGroupPrice)}: {MemberCostGroupPrice}, {nameof(CountryBreakdown)}.Count: {CountryBreakdown?.Count ?? 0}";
}