//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Monta.ApiClient.Generated.Contracts.SponsoredChargePoints;

/// <summary>
/// PublicUser1.
/// </summary>
[GeneratedCode("ApiGenerator", "x.x.x.x")]
public class PublicUser1
{
    /// <summary>
    /// Id of the user.
    /// </summary>
    [Required]
    public long Id { get; set; }

    /// <summary>
    /// Formatted name to be displayed.
    /// </summary>
    [Required]
    public string DisplayName { get; set; }

    /// <inheritdoc />
    public override string ToString()
        => $"{nameof(Id)}: {Id}, {nameof(DisplayName)}: {DisplayName}";
}