//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace ExAsyncEnumerable.Api.Generated.Contracts.Users;

/// <summary>
/// Domain Interface for RequestHandler.
/// Description: Get users.
/// Operation: GetUsers.
/// </summary>
[GeneratedCode("ApiGenerator", "x.x.x.x")]
public interface IGetUsersHandler
{
    /// <summary>
    /// Execute method.
    /// </summary>
    /// <param name="cancellationToken">The cancellation token.</param>
    Task<GetUsersResult> ExecuteAsync(
        CancellationToken cancellationToken = default);
}