//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Monta.ApiClient.Generated.Contracts.Users;

/// <summary>
/// Parameters for operation request.
/// Description: Retrieve users.
/// Operation: GetUsers.
/// </summary>
[GeneratedCode("ApiGenerator", "x.x.x.x")]
public class GetUsersParameters
{
    /// <summary>
    /// page number to retrieve (starts with 0).
    /// </summary>
    public int Page { get; set; } = 0;

    /// <summary>
    /// number of items per page (between 1 and 100, default 10).
    /// </summary>
    public int PerPage { get; set; } = 10;

    /// <summary>
    /// filter user by email.
    /// </summary>
    /// <remarks>
    /// Email validation being enforced.
    /// </remarks>
    [EmailAddress]
    public string Email { get; set; }

    /// <summary>
    /// filter user by phone.
    /// </summary>
    public string Phone { get; set; }

    /// <summary>
    /// Set to 'true' to include deleted users, 'false' otherwise.
    /// </summary>
    public bool IncludeDeleted { get; set; } = false;

    /// <inheritdoc />
    public override string ToString()
        => $"{nameof(Page)}: {Page}, {nameof(PerPage)}: {PerPage}, {nameof(Email)}: {Email}, {nameof(Phone)}: {Phone}, {nameof(IncludeDeleted)}: {IncludeDeleted}";
}