//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace PetStoreApi.Api.Tests.Endpoints.Pets;

[GeneratedCode("ApiGenerator", "x.x.x.x")]
public class ShowPetByIdHandlerStub : IShowPetByIdHandler
{
    public Task<ShowPetByIdResult> ExecuteAsync(
        ShowPetByIdParameters parameters,
        CancellationToken cancellationToken = default)
    {
        var data = new Fixture().Create<Pet>();

        return Task.FromResult(ShowPetByIdResult.Ok(data));
    }
}