//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Scenario2.Api.Generated.Contracts.Accounts;

/// <summary>
/// Parameters for operation request.
/// Description: Set name of account.
/// Operation: SetAccountName.
/// </summary>
[GeneratedCode("ApiGenerator", "x.x.x.x")]
public class SetAccountNameParameters
{
    /// <summary>
    /// The accountId.
    /// </summary>
    [FromRoute(Name = "accountId")]
    [Required]
    public Guid AccountId { get; set; }

    [FromBody]
    [Required]
    public UpdateAccountRequest Request { get; set; }

    /// <inheritdoc />
    public override string ToString()
        => $"{nameof(AccountId)}: {AccountId}, {nameof(Request)}: ({Request})";
}