//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Monta.ApiClient.Generated.Contracts.ChargePoints;

/// <summary>
/// ChargePointOcppLog.
/// </summary>
[GeneratedCode("ApiGenerator", "x.x.x.x")]
public class ChargePointOcppLog
{
    /// <summary>
    /// Timestamp of the OCPP log.
    /// </summary>
    [Required]
    public DateTimeOffset Timestamp { get; set; }

    /// <summary>
    /// Message content of the OCPP log, can be a string or an array of mixed types.
    /// </summary>
    [Required]
    public string Message { get; set; }

    /// <inheritdoc />
    public override string ToString()
        => $"{nameof(Timestamp)}: ({Timestamp}), {nameof(Message)}: {Message}";
}