//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator 2.0.259.29354.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Demo.Api.Generated.Contracts.Tasks;

/// <summary>
/// Describes a single task.
/// </summary>
[GeneratedCode("ApiGenerator", "2.0.259.29354")]
public class Task
{
    public Guid Id { get; set; }

    public string Name { get; set; }

    /// <inheritdoc />
    public override string ToString()
        => $"{nameof(Id)}: {Id}, {nameof(Name)}: {Name}";
}