//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace MontaPartner.ApiClient.Generated.Endpoints.Insights.Interfaces;

/// <summary>
/// Interface for Client Endpoint Result.
/// Description: Retrieve insights about charge points.
/// Operation: GetInsightsChargesChargerReport.
/// </summary>
[GeneratedCode("ApiGenerator", "x.x.x.x")]
public interface IGetInsightsChargesChargerReportEndpointResult : IEndpointResponse
{

    bool IsOk { get; }

    bool IsBadRequest { get; }

    bool IsUnauthorized { get; }

    MontaPageChargesInsightChargerReportDto OkContent { get; }

    string? BadRequestContent { get; }

    string? UnauthorizedContent { get; }
}