//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Monta.ApiClient.Generated.Endpoints.Prices;

/// <summary>
/// Client Endpoint.
/// Description: Retrieve prices forecast.
/// Operation: GetPricesForecast.
/// </summary>
[GeneratedCode("ApiGenerator", "x.x.x.x")]
public class GetPricesForecastEndpoint : IGetPricesForecastEndpoint
{
    private readonly IHttpClientFactory factory;
    private readonly IHttpMessageFactory httpMessageFactory;

    public GetPricesForecastEndpoint(
        IHttpClientFactory factory,
        IHttpMessageFactory httpMessageFactory)
    {
        this.factory = factory;
        this.httpMessageFactory = httpMessageFactory;
    }

    public async Task<GetPricesForecastEndpointResult> ExecuteAsync(
        GetPricesForecastParameters parameters,
        string httpClientName = "Monta-ApiClient",
        CancellationToken cancellationToken = default)
    {
        var client = factory.CreateClient(httpClientName);

        var requestBuilder = httpMessageFactory.FromTemplate("/api/v1/prices/forecast");
        requestBuilder.WithQueryParameter("chargePointId", parameters.ChargePointId);
        requestBuilder.WithQueryParameter("priceGroupId", parameters.PriceGroupId);
        requestBuilder.WithQueryParameter("teamMemberId", parameters.TeamMemberId);

        using var requestMessage = requestBuilder.Build(HttpMethod.Get);
        using var response = await client.SendAsync(requestMessage, cancellationToken);

        var responseBuilder = httpMessageFactory.FromResponse(response);
        responseBuilder.AddSuccessResponse<PricesForecast>(HttpStatusCode.OK);
        responseBuilder.AddErrorResponse<ErrorResponse>(HttpStatusCode.BadRequest);
        responseBuilder.AddErrorResponse<ErrorResponse>(HttpStatusCode.Unauthorized);
        return await responseBuilder.BuildResponseAsync(x => new GetPricesForecastEndpointResult(x), cancellationToken);
    }
}