//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Monta.ApiClient.Generated.Endpoints.Invoices.Interfaces;

/// <summary>
/// Interface for Client Endpoint.
/// Description: Retrieves an invoice by its id.
/// Operation: GetInvoice1.
/// </summary>
[GeneratedCode("ApiGenerator", "x.x.x.x")]
public interface IGetInvoice1Endpoint
{
    /// <summary>
    /// Execute method.
    /// </summary>
    /// <param name="parameters">The parameters.</param>
    /// <param name="httpClientName">The http client name.</param>
    /// <param name="cancellationToken">The cancellation token.</param>
    Task<GetInvoice1EndpointResult> ExecuteAsync(
        GetInvoice1Parameters parameters,
        string httpClientName = "Monta-ApiClient",
        CancellationToken cancellationToken = default);
}