//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Monta.ApiClient.Generated.Contracts.Charges;

/// <summary>
/// Parameters for operation request.
/// Description: Patch an existing charge.
/// Operation: PatchCharge.
/// </summary>
[GeneratedCode("ApiGenerator", "x.x.x.x")]
public class PatchChargeParameters
{
    [Required]
    public long ChargeId { get; set; }

    [Required]
    public PatchCharge Request { get; set; }

    /// <inheritdoc />
    public override string ToString()
        => $"{nameof(ChargeId)}: {ChargeId}, {nameof(Request)}: ({Request})";
}