//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Monta.ApiClient.Generated.Contracts.ChargePointStatistics;

/// <summary>
/// ChargePointStatisticsDto.
/// </summary>
[GeneratedCode("ApiGenerator", "x.x.x.x")]
public class ChargePointStatisticsDto
{
    /// <summary>
    /// Start date of the statistics period.
    /// </summary>
    [Required]
    public DateTimeOffset FromDate { get; set; }

    /// <summary>
    /// End date of the statistics period.
    /// </summary>
    [Required]
    public DateTimeOffset ToDate { get; set; }

    /// <summary>
    /// Total energy consumed during the period (in kWh).
    /// </summary>
    [Required]
    public double TotalEnergyConsumed { get; set; }

    /// <summary>
    /// Total number of charging sessions during the period.
    /// </summary>
    [Required]
    public int TotalSessions { get; set; }

    /// <summary>
    /// Success rate of charging sessions during the period (as a percentage).
    /// </summary>
    [Required]
    public double SessionSuccessRate { get; set; }

    /// <summary>
    /// Percentage of uptime for the system during the period.
    /// </summary>
    public double? SystemUptimePercentage { get; set; }

    /// <summary>
    /// Detailed state for the period.
    /// </summary>
    public List<States> States { get; set; } = new List<States>();

    /// <summary>
    /// Daily statistics for the period.
    /// </summary>
    public List<TimePeriod> Days { get; set; } = new List<TimePeriod>();

    /// <summary>
    /// Monthly statistics for the period.
    /// </summary>
    public List<TimePeriod> Months { get; set; } = new List<TimePeriod>();

    /// <inheritdoc />
    public override string ToString()
        => $"{nameof(FromDate)}: ({FromDate}), {nameof(ToDate)}: ({ToDate}), {nameof(TotalEnergyConsumed)}: {TotalEnergyConsumed}, {nameof(TotalSessions)}: {TotalSessions}, {nameof(SessionSuccessRate)}: {SessionSuccessRate}, {nameof(SystemUptimePercentage)}: {SystemUptimePercentage}, {nameof(States)}.Count: {States?.Count ?? 0}, {nameof(Days)}.Count: {Days?.Count ?? 0}, {nameof(Months)}.Count: {Months?.Count ?? 0}";
}