//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Monta.ApiClient.Generated.Contracts.NestedTeams;

/// <summary>
/// NestedTeamInvite.
/// </summary>
[GeneratedCode("ApiGenerator", "x.x.x.x")]
public class NestedTeamInvite
{
    /// <summary>
    /// Id of the parent team, the one who sends the invite.
    /// </summary>
    [Required]
    public long ParentTeamId { get; set; }

    /// <summary>
    /// Id of the nested team, the one who receives the invite.
    /// </summary>
    [Required]
    public long NestedTeamId { get; set; }

    /// <summary>
    /// Price group applied to the nested team.
    /// </summary>
    [Required]
    public long PriceGroupId { get; set; }

    /// <summary>
    /// Is access granted to all or selected charge points and sites.
    /// </summary>
    [Required]
    public TeamMemberAccess Access { get; set; }

    /// <summary>
    /// List of charge point ids nested team access will be assigned to.
    /// </summary>
    public List<long>? SelectedChargePointIds { get; set; } = new List<long>();

    /// <summary>
    /// List of site ids nested team access will be assigned to.
    /// </summary>
    public List<long>? SelectedSiteIds { get; set; } = new List<long>();

    /// <inheritdoc />
    public override string ToString()
        => $"{nameof(ParentTeamId)}: {ParentTeamId}, {nameof(NestedTeamId)}: {NestedTeamId}, {nameof(PriceGroupId)}: {PriceGroupId}, {nameof(Access)}: ({Access}), {nameof(SelectedChargePointIds)}.Count: {SelectedChargePointIds?.Count ?? 0}, {nameof(SelectedSiteIds)}.Count: {SelectedSiteIds?.Count ?? 0}";
}