//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Monta.ApiClient.Generated.Endpoints.Currencies.Interfaces;

/// <summary>
/// Interface for Client Endpoint Result.
/// Description: Retrieve a list of currencies.
/// Operation: GetCurrencies.
/// </summary>
[GeneratedCode("ApiGenerator", "x.x.x.x")]
public interface IGetCurrenciesEndpointResult : IEndpointResponse
{

    bool IsOk { get; }

    bool IsBadRequest { get; }

    bool IsUnauthorized { get; }

    MontaPageCurrencyDto OkContent { get; }

    string? BadRequestContent { get; }

    string? UnauthorizedContent { get; }
}