//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator 2.0.325.56819.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Demo.Domain;

[GeneratedCode("ApiGenerator", "2.0.325.56819")]
public class DomainRegistration
{
}