using Atc.CodeGeneration.CSharp.Content;

namespace Atc.CodeGeneration.CSharp.Tests.Content.Generators;

public class GenerateContentForInterfaceTests : GenerateContentBaseTests
{
    [Fact]
    public void Scenario1()
    {
        var expectedCode =
@"namespace App.MyNamespace;

public interface MyInterface
{
}";

        var interfaceParameters = new InterfaceParameters(
            HeaderContent: null,
            Namespace: "App.MyNamespace",
            DocumentationTags: null,
            Attributes: null,
            AccessModifier: AccessModifiers.Public,
            InterfaceTypeName: "MyInterface",
            InheritedInterfaceTypeName: null,
            Properties: null,
            Methods: null);

        var sut = new GenerateContentForInterface(
            codeDocumentationTagsGenerator,
            interfaceParameters);

        var generatedCode = sut.Generate();

        Assert.NotNull(generatedCode);
        Assert.Equal(expectedCode, generatedCode);
    }

    [Fact]
    public void Scenario2()
    {
        var expectedCode =
            @"namespace App.MyNamespace;

public interface MyInterface : MyInterfaceBase
{
}";

        var interfaceParameters = new InterfaceParameters(
            HeaderContent: null,
            Namespace: "App.MyNamespace",
            DocumentationTags: null,
            Attributes: null,
            AccessModifier: AccessModifiers.Public,
            InterfaceTypeName: "MyInterface",
            InheritedInterfaceTypeName: "MyInterfaceBase",
            Properties: null,
            Methods: null);

        var sut = new GenerateContentForInterface(
            codeDocumentationTagsGenerator,
            interfaceParameters);

        var generatedCode = sut.Generate();

        Assert.NotNull(generatedCode);
        Assert.Equal(expectedCode, generatedCode);
    }

    [Fact]
    public void Scenario_Demo_SetAccountName_ForDomainRequestHandler()
    {
        const string expectedCode =
            @"//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator X.X.X.X.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Demo.Api.Generated.Contracts.Accounts;

/// <summary>
/// Domain Interface for RequestHandler.
/// Description: Set name of account.
/// Operation: SetAccountName.
/// </summary>
[GeneratedCode(""ApiGenerator"", ""X.X.X.X"")]
public interface ISetAccountNameHandler
{
    /// <summary>
    /// Execute method.
    /// </summary>
    /// <param name=""parameters"">The parameters.</param>
    /// <param name=""cancellationToken"">The cancellation token.</param>
    Task<SetAccountNameResult> ExecuteAsync(
        SetAccountNameParameters parameters,
        CancellationToken cancellationToken = default);
}";

        var documentationTags = new CodeDocumentationTags(
            "Domain Interface for RequestHandler.\r\nDescription: Set name of account.\r\nOperation: SetAccountName.");

        var attributes = new List<AttributeParameters>
        {
            new("GeneratedCode", "\"ApiGenerator\", \"X.X.X.X\""),
        };

        var methodParameters = new List<MethodParameters>
        {
            new(
                DocumentationTags: new CodeDocumentationTags(
                    "Execute method",
                    parameters: new Dictionary<string, string>(StringComparer.Ordinal)
                    {
                        { "parameters", "The parameters." },
                        { "cancellationToken", "The cancellation token." },
                    },
                    remark: null,
                    code: null,
                    example: null,
                    exceptions: null,
                    @return: null),
                Attributes: null,
                AccessModifier: AccessModifiers.None,
                ReturnTypeName: "SetAccountNameResult",
                ReturnGenericTypeName: "Task",
                Name: "ExecuteAsync",
                Parameters: new List<PropertyParameters>()
                {
                    new(
                        DocumentationTags: null,
                        Attributes: null,
                        AccessModifier: AccessModifiers.None,
                        ReturnGenericTypeName: null,
                        ReturnTypeName: "SetAccountNameParameters",
                        Name: "parameters",
                        DefaultValue: null,
                        UseAutoProperty: false,
                        UseSet: false,
                        UseGet: false,
                        UseExpressionBody: false,
                        Content: null),
                    new(
                        DocumentationTags: null,
                        Attributes: null,
                        AccessModifier: AccessModifiers.None,
                        ReturnGenericTypeName: null,
                        ReturnTypeName: "CancellationToken",
                        Name: "cancellationToken",
                        DefaultValue: "default",
                        UseAutoProperty: false,
                        UseSet: false,
                        UseGet: false,
                        UseExpressionBody: false,
                        Content: "default"),
                },
                UseExpressionBody: false,
                Content: null),
        };

        var interfaceParameters = new InterfaceParameters(
            HeaderContent: HeaderContent,
            Namespace: "Demo.Api.Generated.Contracts.Accounts",
            DocumentationTags: documentationTags,
            Attributes: attributes,
            AccessModifier: AccessModifiers.Public,
            InterfaceTypeName: "ISetAccountNameHandler",
            InheritedInterfaceTypeName: null,
            Properties: null,
            Methods: methodParameters);

        var sut = new GenerateContentForInterface(
            codeDocumentationTagsGenerator,
            interfaceParameters);

        var generatedCode = sut.Generate();

        Assert.NotNull(generatedCode);
        Assert.Equal(expectedCode, generatedCode);
    }

    [Fact]
    public void Scenario_Demo_UpdateAccountName_ForDomainRequestHandler()
    {
        var expectedCode =
            @"//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator X.X.X.X.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Demo.Api.Generated.Contracts.Accounts;

/// <summary>
/// Domain Interface for RequestHandler.
/// Description: Update name of account.
/// Operation: UpdateAccountName.
/// </summary>
[GeneratedCode(""ApiGenerator"", ""X.X.X.X"")]
public interface IUpdateAccountNameHandler
{
    /// <summary>
    /// Execute method.
    /// </summary>
    /// <param name=""parameters"">The parameters.</param>
    /// <param name=""cancellationToken"">The cancellation token.</param>
    Task<UpdateAccountNameResult> ExecuteAsync(
        UpdateAccountNameParameters parameters,
        CancellationToken cancellationToken = default);
}";

        var documentationTags = new CodeDocumentationTags(
            "Domain Interface for RequestHandler.\r\nDescription: Update name of account.\r\nOperation: UpdateAccountName.");

        var attributes = new List<AttributeParameters>
        {
            new("GeneratedCode", "\"ApiGenerator\", \"X.X.X.X\""),
        };

        var methodParameters = new List<MethodParameters>
        {
            new(
                DocumentationTags: new CodeDocumentationTags(
                    "Execute method",
                    parameters: new Dictionary<string, string>(StringComparer.Ordinal)
                    {
                        { "parameters", "The parameters." },
                        { "cancellationToken", "The cancellation token." },
                    },
                    remark: null,
                    code: null,
                    example: null,
                    exceptions: null,
                    @return: null),
                Attributes: null,
                AccessModifier: AccessModifiers.None,
                ReturnTypeName: "UpdateAccountNameResult",
                ReturnGenericTypeName: "Task",
                Name: "ExecuteAsync",
                Parameters: new List<PropertyParameters>()
                {
                    new(
                        DocumentationTags: null,
                        Attributes: null,
                        AccessModifier: AccessModifiers.None,
                        ReturnGenericTypeName: null,
                        ReturnTypeName: "UpdateAccountNameParameters",
                        Name: "parameters",
                        DefaultValue: null,
                        UseAutoProperty: false,
                        UseSet: false,
                        UseGet: false,
                        UseExpressionBody: false,
                        Content: null),
                    new(
                        DocumentationTags: null,
                        Attributes: null,
                        AccessModifier: AccessModifiers.None,
                        ReturnGenericTypeName: null,
                        ReturnTypeName: "CancellationToken",
                        Name: "cancellationToken",
                        DefaultValue: "default",
                        UseAutoProperty: false,
                        UseSet: false,
                        UseGet: false,
                        UseExpressionBody: false,
                        Content: "default"),
                },
                UseExpressionBody: false,
                Content: null),
        };

        var interfaceParameters = new InterfaceParameters(
            HeaderContent: HeaderContent,
            Namespace: "Demo.Api.Generated.Contracts.Accounts",
            DocumentationTags: documentationTags,
            Attributes: attributes,
            AccessModifier: AccessModifiers.Public,
            InterfaceTypeName: "IUpdateAccountNameHandler",
            InheritedInterfaceTypeName: null,
            Properties: null,
            Methods: methodParameters);

        var sut = new GenerateContentForInterface(
            codeDocumentationTagsGenerator,
            interfaceParameters);

        var generatedCode = sut.Generate();

        Assert.NotNull(generatedCode);
        Assert.Equal(expectedCode, generatedCode);
    }

    [Fact]
    public void Scenario_Erut_CreateLocation_ForApiClientEndpointResult()
    {
        const string expectedCode =
            @"//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator X.X.X.X.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace ERUT.ApiClient.Generated.Endpoints;

/// <summary>
/// Interface for Client Endpoint Result.
/// Description: Create a new location.
/// Operation: CreateLocation.
/// </summary>
[GeneratedCode(""ApiGenerator"", ""X.X.X.X"")]
public interface ICreateLocationEndpointResult : IEndpointResponse
{
    bool IsOk { get; }

    bool IsBadRequest { get; }

    bool IsUnauthorized { get; }

    bool IsForbidden { get; }

    bool IsInternalServerError { get; }

    Location OkContent { get; }

    ValidationProblemDetails BadRequestContent { get; }

    ProblemDetails UnauthorizedContent { get; }

    ProblemDetails ForbiddenContent { get; }

    ProblemDetails InternalServerErrorContent { get; }
}";

        var documentationTags = new CodeDocumentationTags(
            "Interface for Client Endpoint Result.\r\nDescription: Create a new location.\r\nOperation: CreateLocation.");

        var attributes = new List<AttributeParameters>
        {
            new("GeneratedCode", "\"ApiGenerator\", \"X.X.X.X\""),
        };

        var propertyParameters = new List<PropertyParameters>
        {
            new(
                DocumentationTags: null,
                Attributes: null,
                AccessModifier: AccessModifiers.None,
                ReturnGenericTypeName: null,
                ReturnTypeName: "bool",
                Name: "IsOk",
                DefaultValue: null,
                UseAutoProperty: true,
                UseGet: true,
                UseSet: false,
                UseExpressionBody: false,
                Content: null),
            new(
                DocumentationTags: null,
                Attributes: null,
                AccessModifier: AccessModifiers.None,
                ReturnGenericTypeName: null,
                ReturnTypeName: "bool",
                Name: "IsBadRequest",
                DefaultValue: null,
                UseAutoProperty: true,
                UseGet: true,
                UseSet: false,
                UseExpressionBody: false,
                Content: null),
            new(
                DocumentationTags: null,
                Attributes: null,
                AccessModifier: AccessModifiers.None,
                ReturnGenericTypeName: null,
                ReturnTypeName: "bool",
                Name: "IsUnauthorized",
                DefaultValue: null,
                UseAutoProperty: true,
                UseGet: true,
                UseSet: false,
                UseExpressionBody: false,
                Content: null),
            new(
                DocumentationTags: null,
                Attributes: null,
                AccessModifier: AccessModifiers.None,
                ReturnGenericTypeName: null,
                ReturnTypeName: "bool",
                Name: "IsForbidden",
                DefaultValue: null,
                UseAutoProperty: true,
                UseGet: true,
                UseSet: false,
                UseExpressionBody: false,
                Content: null),
            new(
                DocumentationTags: null,
                Attributes: null,
                AccessModifier: AccessModifiers.None,
                ReturnGenericTypeName: null,
                ReturnTypeName: "bool",
                Name: "IsInternalServerError",
                DefaultValue: null,
                UseAutoProperty: true,
                UseGet: true,
                UseSet: false,
                UseExpressionBody: false,
                Content: null),
            new(
                DocumentationTags: null,
                Attributes: null,
                AccessModifier: AccessModifiers.None,
                ReturnGenericTypeName: null,
                ReturnTypeName: "Location",
                Name: "OkContent",
                DefaultValue: null,
                UseAutoProperty: true,
                UseGet: true,
                UseSet: false,
                UseExpressionBody: false,
                Content: null),
            new(
                DocumentationTags: null,
                Attributes: null,
                AccessModifier: AccessModifiers.None,
                ReturnGenericTypeName: null,
                ReturnTypeName: "ValidationProblemDetails",
                Name: "BadRequestContent",
                DefaultValue: null,
                UseAutoProperty: true,
                UseGet: true,
                UseSet: false,
                UseExpressionBody: false,
                Content: null),
            new(
                DocumentationTags: null,
                Attributes: null,
                AccessModifier: AccessModifiers.None,
                ReturnGenericTypeName: null,
                ReturnTypeName: "ProblemDetails",
                Name: "UnauthorizedContent",
                DefaultValue: null,
                UseAutoProperty: true,
                UseGet: true,
                UseSet: false,
                UseExpressionBody: false,
                Content: null),
            new(
                DocumentationTags: null,
                Attributes: null,
                AccessModifier: AccessModifiers.None,
                ReturnGenericTypeName: null,
                ReturnTypeName: "ProblemDetails",
                Name: "ForbiddenContent",
                DefaultValue: null,
                UseAutoProperty: true,
                UseGet: true,
                UseSet: false,
                UseExpressionBody: false,
                Content: null),
            new(
                DocumentationTags: null,
                Attributes: null,
                AccessModifier: AccessModifiers.None,
                ReturnGenericTypeName: null,
                ReturnTypeName: "ProblemDetails",
                Name: "InternalServerErrorContent",
                DefaultValue: null,
                UseAutoProperty: true,
                UseGet: true,
                UseSet: false,
                UseExpressionBody: false,
                Content: null),
        };

        var interfaceParameters = new InterfaceParameters(
            HeaderContent: HeaderContent,
            Namespace: "ERUT.ApiClient.Generated.Endpoints",
            DocumentationTags: documentationTags,
            Attributes: attributes,
            AccessModifier: AccessModifiers.Public,
            InterfaceTypeName: "ICreateLocationEndpointResult",
            InheritedInterfaceTypeName: "IEndpointResponse",
            Properties: propertyParameters,
            Methods: null);

        var sut = new GenerateContentForInterface(
            codeDocumentationTagsGenerator,
            interfaceParameters);

        var generatedCode = sut.Generate();

        Assert.NotNull(generatedCode);
        Assert.Equal(expectedCode, generatedCode);
    }
}