//------------------------------------------------------------------------------
// This code was auto-generated by ApiGenerator x.x.x.x.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Structure1.Api.Generated.Files.MyContracts;

/// <summary>
/// FilesAsFormDataRequest.
/// </summary>
[GeneratedCode("ApiGenerator", "x.x.x.x")]
public record FilesAsFormDataRequest(
    List<IFormFile> Files);